//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace PoplWS
{
  public partial class C_PES_PLEMENO : XPLiteObject
  {
    decimal fC_PES_PLEMENO_KOD;
    [Key]
    public decimal C_PES_PLEMENO_KOD
    {
      get { return fC_PES_PLEMENO_KOD; }
      set { SetPropertyValue<decimal>("C_PES_PLEMENO_KOD", ref fC_PES_PLEMENO_KOD, value); }
    }
    string fC_PES_PLEMENO_NAZEV;
    [Size(35)]
    public string C_PES_PLEMENO_NAZEV
    {
      get { return fC_PES_PLEMENO_NAZEV; }
      set { SetPropertyValue<string>("C_PES_PLEMENO_NAZEV", ref fC_PES_PLEMENO_NAZEV, value); }
    }
    string fLOGIN;
    [Size(30)]
    public string LOGIN
    {
      get { return fLOGIN; }
      set { SetPropertyValue<string>("LOGIN", ref fLOGIN, value); }
    }
    DateTime fLASTUPDATE;
    public DateTime LASTUPDATE
    {
      get { return fLASTUPDATE; }
      set { SetPropertyValue<DateTime>("LASTUPDATE", ref fLASTUPDATE, value); }
    }
    public C_PES_PLEMENO(Session session) : base(session) { }
  }

}
