//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace PoplWS
{

    public partial class P_POPL_USERS : XPLiteObject
    {
        string fHODNOTA;
        [Size(200)]
        public string HODNOTA
        {
            get { return fHODNOTA; }
            set { SetPropertyValue<string>("HODNOTA", ref fHODNOTA, value); }
        }
        public struct CompoundKey1Struct
        {
            [Size(35)]
            [Persistent("LOGIN")]
            public string LOGIN { get; set; }
            [Size(35)]
            [Persistent("SEKCE")]
            public string SEKCE { get; set; }
            [Size(200)]
            [Persistent("HODNOTA_NAZEV")]
            public string HODNOTA_NAZEV { get; set; }
        }
        [Key, Persistent]
        public CompoundKey1Struct CompoundKey1;

        public P_POPL_USERS(Session session) : base(session) { }

    }

}
