//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace PoplWS
{

  public partial class P_STAT : XPLiteObject
  {
    string fSTAT_KOD;
    [Key]
    [Size(4)]
    public string STAT_KOD
    {
      get { return fSTAT_KOD; }
      set { SetPropertyValue<string>("STAT_KOD", ref fSTAT_KOD, value); }
    }
    string fSTAT_NAZEV;
    [Indexed(Name = @"P_STAT_UK", Unique = true)]
    [Size(64)]
    public string STAT_NAZEV
    {
      get { return fSTAT_NAZEV; }
      set { SetPropertyValue<string>("STAT_NAZEV", ref fSTAT_NAZEV, value); }
    }
    string fSTAT_NAZEV_ENGLISH;
    [Size(64)]
    public string STAT_NAZEV_ENGLISH
    {
      get { return fSTAT_NAZEV_ENGLISH; }
      set { SetPropertyValue<string>("STAT_NAZEV_ENGLISH", ref fSTAT_NAZEV_ENGLISH, value); }
    }
    public P_STAT(Session session) : base(session) { }
  }

}
