//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace PoplWS
{

  public partial class PES_PES : XPLiteObject
  {
    decimal fPES_CIS_PRIZNANI;
    public decimal PES_CIS_PRIZNANI
    {
      get { return fPES_CIS_PRIZNANI; }
      set { SetPropertyValue<decimal>("PES_CIS_PRIZNANI", ref fPES_CIS_PRIZNANI, value); }
    }
    string fPES_JMENO;
    [Size(20)]
    public string PES_JMENO
    {
      get { return fPES_JMENO; }
      set { SetPropertyValue<string>("PES_JMENO", ref fPES_JMENO, value); }
    }
    decimal fPES_PLEMENO;
    public decimal PES_PLEMENO
    {
      get { return fPES_PLEMENO; }
      set { SetPropertyValue<decimal>("PES_PLEMENO", ref fPES_PLEMENO, value); }
    }
    string fPES_POPIS;
    [Size(50)]
    public string PES_POPIS
    {
      get { return fPES_POPIS; }
      set { SetPropertyValue<string>("PES_POPIS", ref fPES_POPIS, value); }
    }
    decimal fPES_ZNAMKA;
    public decimal PES_ZNAMKA
    {
      get { return fPES_ZNAMKA; }
      set { SetPropertyValue<decimal>("PES_ZNAMKA", ref fPES_ZNAMKA, value); }
    }
    string fPES_CIP;
    [Indexed(Name = @"PES_CIP")]
    [Size(20)]
    public string PES_CIP
    {
      get { return fPES_CIP; }
      set { SetPropertyValue<string>("PES_CIP", ref fPES_CIP, value); }
    }
    DateTime fPES_NAROZEN;
    public DateTime PES_NAROZEN
    {
      get { return fPES_NAROZEN; }
      set { SetPropertyValue<DateTime>("PES_NAROZEN", ref fPES_NAROZEN, value); }
    }
    DateTime fPES_DRZEN_OD;
    public DateTime PES_DRZEN_OD
    {
      get { return fPES_DRZEN_OD; }
      set { SetPropertyValue<DateTime>("PES_DRZEN_OD", ref fPES_DRZEN_OD, value); }
    }
    DateTime fPES_POPL_OD;
    public DateTime PES_POPL_OD
    {
      get { return fPES_POPL_OD; }
      set { SetPropertyValue<DateTime>("PES_POPL_OD", ref fPES_POPL_OD, value); }
    }
    DateTime fPES_POPL_DO;
    public DateTime PES_POPL_DO
    {
      get { return fPES_POPL_DO; }
      set { SetPropertyValue<DateTime>("PES_POPL_DO", ref fPES_POPL_DO, value); }
    }
    DateTime fPES_SLEVA_OD;
    public DateTime PES_SLEVA_OD
    {
      get { return fPES_SLEVA_OD; }
      set { SetPropertyValue<DateTime>("PES_SLEVA_OD", ref fPES_SLEVA_OD, value); }
    }
    DateTime fPES_SLEVA_DO;
    public DateTime PES_SLEVA_DO
    {
      get { return fPES_SLEVA_DO; }
      set { SetPropertyValue<DateTime>("PES_SLEVA_DO", ref fPES_SLEVA_DO, value); }
    }
    DateTime fPES_ZMENA_OD;
    public DateTime PES_ZMENA_OD
    {
      get { return fPES_ZMENA_OD; }
      set { SetPropertyValue<DateTime>("PES_ZMENA_OD", ref fPES_ZMENA_OD, value); }
    }
    DateTime fPES_OCKOVAN;
    public DateTime PES_OCKOVAN
    {
      get { return fPES_OCKOVAN; }
      set { SetPropertyValue<DateTime>("PES_OCKOVAN", ref fPES_OCKOVAN, value); }
    }
    decimal fPES_UCEL;
    public decimal PES_UCEL
    {
      get { return fPES_UCEL; }
      set { SetPropertyValue<decimal>("PES_UCEL", ref fPES_UCEL, value); }
    }
    decimal fPES_SAZPOPL_SAZBA;
    public decimal PES_SAZPOPL_SAZBA
    {
      get { return fPES_SAZPOPL_SAZBA; }
      set { SetPropertyValue<decimal>("PES_SAZPOPL_SAZBA", ref fPES_SAZPOPL_SAZBA, value); }
    }
    string fPES_POHLAVI;
    [Size(4)]
    public string PES_POHLAVI
    {
      get { return fPES_POHLAVI; }
      set { SetPropertyValue<string>("PES_POHLAVI", ref fPES_POHLAVI, value); }
    }
    char fPES_OSVOBOZEN;
    public char PES_OSVOBOZEN
    {
      get { return fPES_OSVOBOZEN; }
      set { SetPropertyValue<char>("PES_OSVOBOZEN", ref fPES_OSVOBOZEN, value); }
    }
    DateTime fPES_DRZEN_DO;
    public DateTime PES_DRZEN_DO
    {
      get { return fPES_DRZEN_DO; }
      set { SetPropertyValue<DateTime>("PES_DRZEN_DO", ref fPES_DRZEN_DO, value); }
    }
    string fPES_POZNAMKA;
    public string PES_POZNAMKA
    {
      get { return fPES_POZNAMKA; }
      set { SetPropertyValue<string>("PES_POZNAMKA", ref fPES_POZNAMKA, value); }
    }
    string fPES_TET;
    [Size(13)]
    public string PES_TET
    {
      get { return fPES_TET; }
      set { SetPropertyValue<string>("PES_TET", ref fPES_TET, value); }
    }
    string fPES_CIP2;
    [Size(20)]
    public string PES_CIP2
    {
      get { return fPES_CIP2; }
      set { SetPropertyValue<string>("PES_CIP2", ref fPES_CIP2, value); }
    }
    DateTime fPES_ZNAMKA_VYD;
    public DateTime PES_ZNAMKA_VYD
    {
      get { return fPES_ZNAMKA_VYD; }
      set { SetPropertyValue<DateTime>("PES_ZNAMKA_VYD", ref fPES_ZNAMKA_VYD, value); }
    }
    decimal fPES_BARVA;
    public decimal PES_BARVA
    {
      get { return fPES_BARVA; }
      set { SetPropertyValue<decimal>("PES_BARVA", ref fPES_BARVA, value); }
    }
    DateTime fPES_SLEVAC_OD;
    public DateTime PES_SLEVAC_OD
    {
      get { return fPES_SLEVAC_OD; }
      set { SetPropertyValue<DateTime>("PES_SLEVAC_OD", ref fPES_SLEVAC_OD, value); }
    }
    DateTime fPES_SLEVAC_DO;
    public DateTime PES_SLEVAC_DO
    {
      get { return fPES_SLEVAC_DO; }
      set { SetPropertyValue<DateTime>("PES_SLEVAC_DO", ref fPES_SLEVAC_DO, value); }
    }
    decimal fPES_SLEVAC_KC;
    public decimal PES_SLEVAC_KC
    {
      get { return fPES_SLEVAC_KC; }
      set { SetPropertyValue<decimal>("PES_SLEVAC_KC", ref fPES_SLEVAC_KC, value); }
    }
    int fPES_UQ_ID;
    public int PES_UQ_ID
    {
      get { return fPES_UQ_ID; }
      set { SetPropertyValue<int>("PES_UQ_ID", ref fPES_UQ_ID, value); }
    }
    string fENTRYLOGIN;
    [Size(32)]
    public string ENTRYLOGIN
    {
      get { return fENTRYLOGIN; }
      set { SetPropertyValue<string>("ENTRYLOGIN", ref fENTRYLOGIN, value); }
    }
    DateTime fENTRYDATE;
    public DateTime ENTRYDATE
    {
      get { return fENTRYDATE; }
      set { SetPropertyValue<DateTime>("ENTRYDATE", ref fENTRYDATE, value); }
    }
    string fLASTLOGIN;
    [Size(32)]
    public string LASTLOGIN
    {
      get { return fLASTLOGIN; }
      set { SetPropertyValue<string>("LASTLOGIN", ref fLASTLOGIN, value); }
    }
    DateTime fLASTUPDATE;
    public DateTime LASTUPDATE
    {
      get { return fLASTUPDATE; }
      set { SetPropertyValue<DateTime>("LASTUPDATE", ref fLASTUPDATE, value); }
    }
    public struct CompoundKey1Struct
    {
      [Size(15)]
      [Persistent("PES_MAJITEL_ICO")]
      public string PES_MAJITEL_ICO { get; set; }
      [Persistent("PES_ID")]
      public decimal PES_ID { get; set; }
      [Size(1)]
      [Persistent("PES_MAJITEL_PERIODA")]
      public string PES_MAJITEL_PERIODA { get; set; }
    }
    [Indexed(Name = @"PK_PES", Unique = true)]
    [Key, Persistent]
    public CompoundKey1Struct CompoundKey1;
    public PES_PES(Session session) : base(session) { }
  }

}
