//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace PoplWS
{

  [Indices(@"CompoundKey1;MAJITEL_AKTIVNI")]
  public partial class PES_MAJITEL : XPLiteObject
  {
    string fMAJITEL_VYSTUP;
    [Size(10)]
    public string MAJITEL_VYSTUP
    {
      get { return fMAJITEL_VYSTUP; }
      set { SetPropertyValue<string>("MAJITEL_VYSTUP", ref fMAJITEL_VYSTUP, value); }
    }
    char fMAJITEL_AKTIVNI;
    public char MAJITEL_AKTIVNI
    {
      get { return fMAJITEL_AKTIVNI; }
      set { SetPropertyValue<char>("MAJITEL_AKTIVNI", ref fMAJITEL_AKTIVNI, value); }
    }
    string fENTRYLOGIN;
    [Size(32)]
    public string ENTRYLOGIN
    {
      get { return fENTRYLOGIN; }
      set { SetPropertyValue<string>("ENTRYLOGIN", ref fENTRYLOGIN, value); }
    }
    DateTime fENTRYDATE;
    public DateTime ENTRYDATE
    {
      get { return fENTRYDATE; }
      set { SetPropertyValue<DateTime>("ENTRYDATE", ref fENTRYDATE, value); }
    }
    string fLASTLOGIN;
    [Size(32)]
    public string LASTLOGIN
    {
      get { return fLASTLOGIN; }
      set { SetPropertyValue<string>("LASTLOGIN", ref fLASTLOGIN, value); }
    }
    DateTime fLASTUPDATE;
    public DateTime LASTUPDATE
    {
      get { return fLASTUPDATE; }
      set { SetPropertyValue<DateTime>("LASTUPDATE", ref fLASTUPDATE, value); }
    }
    public struct CompoundKey1Struct
    {
      [Size(15)]
      [Persistent("MAJITEL_ICO")]
      public string MAJITEL_ICO { get; set; }
      [Size(1)]
      [Persistent("MAJITEL_PERIODA")]
      public string MAJITEL_PERIODA { get; set; }
    }
    [Indexed(Name = @"PK_PES_MAJITEL", Unique = true)]
    [Key, Persistent]
    public CompoundKey1Struct CompoundKey1;
    public PES_MAJITEL(Session session) : base(session) { }
  }

}
